name: actiondebug
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  build_win32:
    runs-on: windows-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3
    - run: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat'
      shell: cmd
    - run: '& ".\build-product-magpath.ps1"'
    - uses: dlemstra/code-sign-action@v1
      with:
        certificate: '${{ secrets.CERTIFICATE }}'
        password: '${{ secrets.CERTIFICATE_PASSWORD }}'
        folder: 'code\Release'
        recursive: true
        files: |
          Magnolia-IDE.exe
