name: actiondebug
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:

  build_bla:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -fy python2.7 python2.7-dev python-pip
    - run: python2 -m pip install pytest
    - run: pytest
