name: actiondebug
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  build_win32:
    runs-on: windows-2022
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - run: '& ".\build-product-magpath.ps1"'
    - uses: dlemstra/code-sign-action@v1
      with:
        certificate: '${{ secrets.CERTIFICATE }}'
        password: '${{ secrets.CERTIFICATE_PASSWORD }}'
        folder: 'code/Release'
        recursive: true
        files: |
          Magnolia-IDE.exe
